[project]
name = "tama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "openai>=1.10.0",
    "pytest>=7.4.0",
    "pytest-mock>=3.10.0",
    "python-dotenv>=1.0.0",
    "rich>=13.0.0",
    "typer>=0.9.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[project.scripts]
tama = "cli.main:app"
